require:
  - rubocop-rails

inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.7

Performance:
  enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
    - db/schema.rb

Rails/HelperInstanceVariable:
  Enabled: false

Rails/TimeZone:
  Enabled: false
