inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.4

Performance:
  enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
    - db/schema.rb
