---
name: Downloads on https://git-scm.com not working
description: If you are experiencing problems downloading Git from https://git-scm.com/downloads.
labels: [bug]

body:
  # Please follow the instructions below.
  # An issue properly explained is solved much faster!
  - type: textarea
    attributes:
      # Provide a brief summary of the issue in the issue title.
      label: Which download is failing?
      placeholder: Tell us in which page and version is the download broken.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem
      placeholder: Explain the problem clearly.
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system and browser
      description: Which operating system and browser are you using?
    validations:
      required: true
  - type: textarea
    attributes:
      # Provide a detailed list of steps.
      # In the rare cases where this is not possible, we will accept a detailed set of instructions.
      label: Steps to reproduce
      placeholder: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other details
      placeholder: Include as many relevant details you may find relevant.
      render: shell
