#!/bin/sh

# Set up Ruby dependencies and the local SQLite database.

bundle check 2>&1 > /dev/null || bundle install --binstubs --path vendor/gems
bundle exec rake db:migrate

# We need a temp directory.

mkdir -p tmp

# Make a local git clone and index manpages.

test -d tmp/git || git clone git://github.com/git/git.git tmp/git
bundle exec rake local_index GIT_REPO=tmp/git/.git
