#!/bin/sh

set -e

export BUNDLE_WITHOUT=production
export RAILS_ROOT=$(cd "$(dirname $0)"/.. && pwd)
export RAILS_ENV="test"
export PATH="/usr/share/rbenv/shims:$PATH"
export RBENV_VERSION="1.9.3-p194"

cd $RAILS_ROOT
script/bootstrap && bundle exec rspec
