#!/usr/bin/env ruby
# frozen_string_literal: true

require "asciidoctor"
require "pp"

file_path = File.expand_path("./spec/data/git-diff.txt")

content = File.read(file_path)
content.gsub!(/::(.*)\.txt/, "::\\1")
doc = Asciidoctor::Document.new(content)
html = doc.render
html.gsub!(/linkgit:(.*)\[(\d+)\]/) do |line|
  x = /^linkgit:(.*)\[(\d+)\]/.match(line)
  line = "<a href='/docs/#{x[1]}'>#{x[1]}[#{x[2]}]</a>"
end

File.open("./git-diff.html", "w+") do |f|
 f.write html
end
