#!/bin/sh

DST=public/book/en/v2
: ${PROGIT:=../progit2}

if ! test -d "$PROGIT"; then
	echo >&2 "fatal: you need a checkout of the progit2 repo at $PROGIT"
	exit 1
fi

import() {
	find $PROGIT/book/*/$1 -type f |
	while read -r src; do
		cp "$src" "$2"
	done
}

import images $DST/images
import callouts $DST/callouts
