#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Setting up DB..."
bin/rake db:create db:reset

echo "==> Building Git Docs..."
if ! [ -d "../git" ]; then
  git clone git://github.com/git/git.git ../git
fi

bin/rake local_index

echo "==> Fetching downloads..."
bin/rake downloads

if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
  # Only things for a development environment will run inside here
  # Do things that need to be done to the application to set up for the first
  # time. Or things needed to be run to to reset the application back to first
  # use experience. These things are scoped to the application's domain.
  true
fi

echo "==> App is now ready to go!"
