#!/usr/bin/env ruby

require 'httparty'
require 'nokogiri'
require 'open-uri'

url = if ARGV[0]
  then
    puts "Using localhost"
    "http://localhost:3000/downloads/guis"
  else
    puts "Using live site"
    "https://git-scm.com/downloads/guis"
  end

page = HTTParty.get(url)

parse_page = Nokogiri::HTML(page)
h4s = parse_page.css('h4')

guis = h4s.map do |elem|
  trend_name = elem.attribute('data-trend')
  trend_name ? trend_name.value : elem.child.content
end

puts "\n=== GUIs (#{guis.size}) ==="
puts guis

encoded = guis.map { |e| URI::encode(e) }

minIndex = 0
maxIndex = 4
trend_groups = []

last_idx = encoded.size - 1
while minIndex < last_idx do
  trend_groups.push([minIndex, [maxIndex, last_idx].min])
  minIndex += 4
  maxIndex += 4
end

trend_urls = trend_groups.map do |min_max|
  terms = (min_max[0]..min_max[1]).map { |idx| encoded[idx] }
  "https://trends.google.pt/trends/explore?cat=31&q=#{terms.join(",")}&hl=en_us"
end

puts "\n=== Trends URLs (#{trend_urls.size}) ==="
puts trend_urls
