name: Purge Cloudflare Cache

on:
  workflow_dispatch:

jobs:
  purge-cache:
    concurrency:
      group: "purge-cache"
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare cache
        shell: bash
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        if: env.CLOUDFLARE_TOKEN != ''
        run: |
          curl "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache" \
            -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{ "purge_everything": true }'


